tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "rcmdnk/rcmdnkpac"
tap "sanemat/font"
brew "anyenv"
brew "awscli"
brew "bat"
brew "cocoapods"
brew "dep"
brew "direnv"
brew "fd"
brew "fzf"
brew "ghq"
brew "git"
brew "git-now"
brew "jq"
brew "mackup"
brew "macvim"
brew "mas"
brew "mysql-client@5.7"
brew "redis"
brew "ripgrep"
brew "rmtrash"
brew "starship"
brew "terraform"
brew "tmux"
brew "tree"
brew "wget"
brew "yarn"
brew "zsh"
brew "sanemat/font/ricty", args: ["with-powerline"]
cask "alfred"
cask "appcleaner"
cask "docker"
cask "dropbox"
cask "google-japanese-ime"
cask "iterm2"
cask "jetbrains-toolbox"
cask "karabiner-elements"
cask "notion"
cask "shiftit"
cask "trailer"
cask "zoomus"
mas "LadioCast", id: 411213048
mas "LINE", id: 539883307
mas "Mate Translate", id: 1005088137
mas "PicGIF Lite", id: 844918735
mas "ScreenBrush", id: 1233965871
mas "Skitch", id: 425955336
mas "Slack", id: 803453959
mas "Spark", id: 1176895641
mas "TweetDeck", id: 485812721
